name: check Torizon updates

on:
  schedule:
      - cron: '0 6 * * 1' # Run every monday at 6:00 AM UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-torizon-updates:
    name: Check Torizon updates
    runs-on: [self-hosted]
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        manufacturer: [ti, nxp]

    steps:
      - name: Checkout torizon-optologic
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
          fetch-depth: 0
          ref: 'torizon-${{ matrix.manufacturer }}-7.x.y'

      - name: Check for toradex revision updates
        id: check-for-toradex-revision-updates
        run: |
            set +e
            .github/scripts/check-toradex-revision-updates.sh
            exit_code="$?"
            echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
            if [[ $exit_code -eq 1 ]]; then
                exit 1
            fi

      - name: Check for torizon core builder updates
        run: |
            set +e
            .github/scripts/check-torizon-core-builder-updates.sh
            exit_code="$?"
            echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
            if [[ $exit_code -eq 1 ]]; then
                exit 1
            fi

      -  name: Check for closed pull request on the torizon-${{ matrix.manufacturer }}-update/${{steps.check-for-toradex-revision-updates.outputs.latest_stable_tag}} branch
         if: steps.check-for-toradex-revision-updates.outputs.exit_code == '2'
         id: find-torizon-update-pull-request
         uses: juliangruber/find-pull-request-action@v1
         with:
           state: closed
           branch: torizon-${{ matrix.manufacturer }}-update/${{steps.check-for-toradex-revision-updates.outputs.latest_stable_tag}}

      - name: Read PR template
        if: steps.check-for-toradex-revision-updates.outputs.exit_code == '2' && steps.find-torizon-update-pull-request.outputs.matching-pr-count == 0
        id: pr_template
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat .github/pull_request_template.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Open a pull request with the updated torizon
        if: steps.check-for-toradex-revision-updates.outputs.exit_code == '2' && steps.find-revision-pull-request.outputs.matching-pr-count == 0
        id: cpr-bsp
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.auto_update_token }}
          commit-message: ".github:workflows: update to Toradex revision ${{steps.check-for-toradex-revision-updates.outputs.latest_stable_tag}} version"
          title: "${{ matrix.manufacturer }}: Update Toradex revision to the ${{steps.check-for-toradex-revision-updates.outputs.latest_stable_tag}} version"
          body: |
              # Description
              This pull request updates the Toradex revision to the ${{steps.check-for-toradex-revision-updates.outputs.latest_stable_tag}} version and the corresponding Torizon Core Builder version.
              ${{ steps.pr_template.outputs.body }}
          branch: torizon-${{ matrix.manufacturer }}-update/${{steps.check-for-toradex-revision-updates.outputs.latest_stable_tag}}
          signoff: true

      - name: Output pull request details
        if: ${{ steps.cpr-bsp.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr-bsp.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr-bsp.outputs.pull-request-url }}"
